## Selecting data

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('DataExtraction/players_20.csv',encoding='utf-8')
df.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

In [3]:
#set index
df = df.set_index('short_name')
df.head()

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

In [4]:
#select columns
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club','overall']]
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91

## Selecting with a single value

loc[row_label,column_label]

In [5]:
#get all data about L.Messi
df.loc['L. Messi']

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
overall                                    94
Name: L. Messi, dtype: object

In [6]:
#get the height of L.Messi
df.loc['L. Messi','height_cm']

np.int64(170)

In [7]:
#Weight of C.Ronaldo
df.loc['Cristiano Ronaldo','weight_kg']

np.int64(83)

In [8]:
#get all rows in height column
df.loc[:,'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [9]:
#Get all columns that correspond to the name L. Messi
df.loc['L. Messi',:]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
overall                                    94
Name: L. Messi, dtype: object

## Selecting with a list of values

In [10]:
#Get all data about L. Messi and Cristiano Ronaldo
df.loc[['L. Messi','Cristiano Ronaldo']]

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93

In [11]:
#get both their heights
df.loc[['L. Messi','Cristiano Ronaldo'],'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [12]:
#height and weight of L. Messi
df.loc['L. Messi',['height_cm','weight_kg']]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [13]:
#height and weight of both
df.loc[['L. Messi','Cristiano Ronaldo'],['height_cm','weight_kg']]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

## Selecting a range of data with a slice
start:stop:step ("Stop" INDEX IS INCLUDED)

In [14]:
#Slice column labels
players = ['L. Messi','Cristiano Ronaldo']
df.loc[players,'age':'club']

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [15]:
df.head(15)

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City,91
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona,90
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool,90
L. Modrić,Luka Modrić,33,1985-09-09,172,66,Croatia,Real Madrid,90
M. Salah,Mohamed Salah Ghaly,27,1992-06-15,175,71,Egypt,Liverpool,90
K. Mbappé,Kylian Mbappé,20,1998-12-20,178,73,France,Paris Saint-Germain,89
K. Koulibaly,Kalidou Koulibaly,28,1991-06-20,187,89,Senegal,Napoli,89
H. Kane,Harry Kane,25,1993-07-28,188,89,England,Tottenham Hotspur,89
Alisson,Alisson Ramses Becker,26,1992-10-02,191,91,Brazil,Liverpool,89
De Gea,David De Gea Quintana,28,1990-11-07,192,82,Spain,Manchester United,89

In [45]:
#Slice index labels
columns = ['age','dob','height_cm','weight_kg']

df.loc['Neymar Jr':'Alisson',columns]

               age         dob  height_cm  weight_kg
short_name
Neymar Jr       27  1992-02-05        175         68
J. Oblak        26  1993-01-07        188         87
E. Hazard       28  1991-01-07        175         74
K. De Bruyne    28  1991-06-28        181         70
M. ter Stegen   27  1992-04-30        187         85
V. van Dijk     27  1991-07-08        193         92
L. Modrić       33  1985-09-09        172         66
M. Salah        27  1992-06-15        175         71
K. Mbappé       20  1998-12-20        178         73
K. Koulibaly    28  1991-06-20        187         89
H. Kane         25  1993-07-28        188         89
Alisson         26  1992-10-02        191         91

## Selecting with conditions

In [58]:
#Selecting players with height > 199cm
columns = ['age','dob','height_cm','weight_kg','overall']
df.loc[df['height_cm']>199,columns].sort_values(by='overall',ascending=False)

                     age         dob  height_cm  weight_kg  overall
short_name
N. Pope               27  1992-04-19        200         76       79
L. Kalinić            29  1990-04-03        201         99       75
F. Forster            31  1988-03-17        201         93       73
C. Pantilimon         32  1987-02-01        203         96       73
K. Letica             22  1997-02-11        201         96       71
P. Onuachu            25  1994-05-28        201         82       71
H. Veerman            28  1991-02-26        201         90       71
V. Milinković-Savić   22  1997-02-20        202         92       70
A. Koșelev            25  1993-11-19        200         90       70
T. Chorý              24  1995-01-26        200        101       70
L. Traoré             29  1990-05-20        203         87       70
A. Vukotić            23  1995-07-22        201         95       69
S. Kalajdžić          21  1997-07-07        200         76       68
A. Sjöberg            28  1991-03-08        201         95       68
S. Makienok           28  1990-11-21        201         94       67
A. Ba                 25  1994-02-08        203         94       67
K. Sidibé             20  1999-01-28        200         85       67
K. Scherpen           19  2000-01-23        202         85       67
T. Holý               27  1991-12-10        205        102       66
E. Johansen           26  1992-07-12        201        102       64
T. Cissokho           19  2000-02-08        200         88       63
A. Chapman            29  1990-05-29        203         92       63
M. Qvist              26  1993-04-22        203         94       63
H. Souttar            20  1998-10-22        200         79       61
R. Laidlaw            26  1992-07-12        201         85       61
J. Karlstrøm          22  1997-01-09        200         90       60
J. Brattberg          22  1996-12-28        200         96       59
K. Athiu              26  1992-08-05        201         85       59
S. Brolin             18  2000-09-29        202         85       55
M. Casey              19  1999-11-13        203         80       54
R. Källman            20  1999-02-12        200        100       54
D. Thiam              21  1998-03-09        202         87       51

In [65]:
#Selecting players with height > 199cm from England
df.loc[(df['height_cm']>199) & (df['nationality'] == 'England'),columns].sort_values(by='overall',ascending=False)

            age         dob  height_cm  weight_kg  overall
short_name
N. Pope      27  1992-04-19        200         76       79
F. Forster   31  1988-03-17        201         93       73
A. Chapman   29  1990-05-29        203         92       63
M. Casey     19  1999-11-13        203         80       54

In [68]:
#Selecting players with height > 199cm from England OR Sweden
df.loc[(df['height_cm']>199) & ((df['nationality'] == 'England') | (df['nationality'] == 'Sweden')),columns].sort_values(by='overall',ascending=False)

              age         dob  height_cm  weight_kg  overall
short_name
N. Pope        27  1992-04-19        200         76       79
F. Forster     31  1988-03-17        201         93       73
A. Sjöberg     28  1991-03-08        201         95       68
A. Chapman     29  1990-05-29        203         92       63
J. Brattberg   22  1996-12-28        200         96       59
S. Brolin      18  2000-09-29        202         85       55
M. Casey       19  1999-11-13        203         80       54

In [69]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91

## iloc method

### Selecting with a single value
iloc[row_position,column_position]

In [78]:
#get height of L. Messi
row_num = df.index.get_loc('L. Messi')
column_num = df.columns.get_loc('height_cm')

df.iloc[row_num,column_num] #same as df.iloc[0,3]

170

In [80]:
#weight of Cristiano
df.iloc[df.index.get_loc('Cristiano Ronaldo'),df.columns.get_loc('weight_kg')]

83

In [81]:
#get all rows in the 'height_cm' column
df.iloc[:,3]

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [83]:
#get all messi columns
df.iloc[row_num,:]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
overall                                    94
Name: L. Messi, dtype: object

### Selecting with a list of values

In [84]:
#Get all data about Messi and CR7
df.iloc[[0,1],:]

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93

In [85]:
#Get height of messi and ronaldo
df.iloc[[0,1],3]

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [86]:
#height and weight of messi and ronaldo
df.iloc[[0,1],[3,4]]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

### Selecting range of data with a slice
start:stop (Stop is excluded)

In [91]:
# slice columns labels age/club
# players = ['L. Messi','Cristiano Ronaldo']
players = [0,1]
df.iloc[players, 1:7]

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [93]:
#slice index labels(top 1 to 10)
#columns = ['age','dob','height_cm','weight_kg']
# get top 1 to 10 players
df.iloc[0:10,1:5]

                   age         dob  height_cm  weight_kg
short_name
L. Messi            32  1987-06-24        170         72
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. Modrić           33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71

### selecting with conditions
iloc cannot accept boolean series but only a boolean list. have to use list() function to convert series into a boolean list

In [94]:
#one condition: select players with height >199cm
#columns = ['age','dob','height_cm','weight_kg'] -> 1:5
list_from_series = list(df['height_cm']>199)
df.iloc[list_from_series,1:5]

                     age         dob  height_cm  weight_kg
short_name
N. Pope               27  1992-04-19        200         76
L. Kalinić            29  1990-04-03        201         99
F. Forster            31  1988-03-17        201         93
C. Pantilimon         32  1987-02-01        203         96
K. Letica             22  1997-02-11        201         96
P. Onuachu            25  1994-05-28        201         82
H. Veerman            28  1991-02-26        201         90
V. Milinković-Savić   22  1997-02-20        202         92
A. Koșelev            25  1993-11-19        200         90
T. Chorý              24  1995-01-26        200        101
L. Traoré             29  1990-05-20        203         87
A. Vukotić            23  1995-07-22        201         95
S. Kalajdžić          21  1997-07-07        200         76
A. Sjöberg            28  1991-03-08        201         95
K. Scherpen           19  2000-01-23        202         85
K. Sidibé             20  1999-01-28        200         85
A. Ba                 25  1994-02-08        203         94
S. Makienok           28  1990-11-21        201         94
T. Holý               27  1991-12-10        205        102
E. Johansen           26  1992-07-12        201        102
T. Cissokho           19  2000-02-08        200         88
A. Chapman            29  1990-05-29        203         92
M. Qvist              26  1993-04-22        203         94
H. Souttar            20  1998-10-22        200         79
R. Laidlaw            26  1992-07-12        201         85
J. Karlstrøm          22  1997-01-09        200         90
J. Brattberg          22  1996-12-28        200         96
K. Athiu              26  1992-08-05        201         85
S. Brolin             18  2000-09-29        202         85
M. Casey              19  1999-11-13        203         80
R. Källman            20  1999-02-12        200        100
D. Thiam              21  1998-03-09        202         87

In [99]:
#multiple conditions
#players above 199cm from england and sweden
conditions_list = list((df['height_cm']>199) & ((df['nationality'] == 'England') | (df['nationality'] == 'Sweden')))
df.iloc[conditions_list,1:5]

              age         dob  height_cm  weight_kg
short_name
N. Pope        27  1992-04-19        200         76
F. Forster     31  1988-03-17        201         93
A. Sjöberg     28  1991-03-08        201         95
A. Chapman     29  1990-05-29        203         92
J. Brattberg   22  1996-12-28        200         96
S. Brolin      18  2000-09-29        202         85
M. Casey       19  1999-11-13        203         80