In [40]:
import pandas as pd
import numpy as np
df = pd.read_csv('DataExtraction/players_20.csv',encoding='utf-8')
df.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

In [41]:
df = df.set_index('short_name')
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club','overall']]
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91

### Set value to one cell

In [42]:
#Update L. Messi height
df.loc['L. Messi', 'height_cm'] = 175
df.head(3)

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,175,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92

### Set value to entire column

In [44]:
df.loc['L. Messi','height_cm'] = 170
early_backup = df.copy()
early_backup

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91
...,...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48

In [45]:
#set all players height to 193
df.loc[:,'height_cm'] = 193
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,193,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,193,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,193,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,193,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,193,74,Belgium,Real Madrid,91

### Set value to entire row

In [51]:
early_backup.head(3)

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92

In [48]:
df = early_backup

In [54]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91
...,...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48

In [56]:
#get all columns that correspond to player ranked last in fifa
df.iloc[-1,:]

long_name                         潘喜明
age                                26
dob                        1993-01-11
height_cm                         182
weight_kg                          78
nationality                  China PR
club           Hebei China Fortune FC
overall                            48
Name: Pan Ximing, dtype: object

In [58]:
#Set null values to all columns that correspond to the lowest ranked player
df.iloc[-1,:] = np.nan

In [59]:
df.tail()

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
Shao Shuai,邵帅,22.0,1997-03-10,186.0,79.0,China PR,Beijing Renhe FC,48.0
Xiao Mingjie,Mingjie Xiao,22.0,1997-01-01,177.0,66.0,China PR,Shanghai SIPG FC,48.0
Zhang Wei,张威,19.0,2000-05-16,186.0,75.0,China PR,Hebei China Fortune FC,48.0
Wang Haijian,汪海健,18.0,2000-08-02,185.0,74.0,China PR,Shanghai Greenland Shenhua FC,48.0
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Set value to multiple cells

In [64]:
#set values to all items matching the list of labels
df.loc[['L. Messi','Cristiano Ronaldo'],['height_cm']] = 172
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,172.0,72.0,Argentina,FC Barcelona,94.0
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,172.0,83.0,Portugal,Juventus,93.0
Neymar Jr,Neymar da Silva Santos Junior,27.0,1992-02-05,175.0,68.0,Brazil,Paris Saint-Germain,92.0
J. Oblak,Jan Oblak,26.0,1993-01-07,188.0,87.0,Slovenia,Atlético Madrid,91.0
E. Hazard,Eden Hazard,28.0,1991-01-07,175.0,74.0,Belgium,Real Madrid,91.0

In [67]:
df.loc['L. Messi','height_cm'] = 170
df.loc[['Cristiano Ronaldo'],['height_cm']] = 187
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,170.0,72.0,Argentina,FC Barcelona,94.0
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,187.0,83.0,Portugal,Juventus,93.0
Neymar Jr,Neymar da Silva Santos Junior,27.0,1992-02-05,175.0,68.0,Brazil,Paris Saint-Germain,92.0
J. Oblak,Jan Oblak,26.0,1993-01-07,188.0,87.0,Slovenia,Atlético Madrid,91.0
E. Hazard,Eden Hazard,28.0,1991-01-07,175.0,74.0,Belgium,Real Madrid,91.0

### Set values for rows matching a condition

In [69]:
columns = ['age','dob','height_cm','weight_kg']

df['height_cm'] > 180

df.loc[df['height_cm'] > 180, columns] = 0

df

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,170.0,72.0,Argentina,FC Barcelona,94.0
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,0.0,0,0.0,0.0,Portugal,Juventus,93.0
Neymar Jr,Neymar da Silva Santos Junior,27.0,1992-02-05,175.0,68.0,Brazil,Paris Saint-Germain,92.0
J. Oblak,Jan Oblak,0.0,0,0.0,0.0,Slovenia,Atlético Madrid,91.0
E. Hazard,Eden Hazard,28.0,1991-01-07,175.0,74.0,Belgium,Real Madrid,91.0
...,...,...,...,...,...,...,...,...
Shao Shuai,邵帅,0.0,0,0.0,0.0,China PR,Beijing Renhe FC,48.0
Xiao Mingjie,Mingjie Xiao,22.0,1997-01-01,177.0,66.0,China PR,Shanghai SIPG FC,48.0
Zhang Wei,张威,0.0,0,0.0,0.0,China PR,Hebei China Fortune FC,48.0
Wang Haijian,汪海健,0.0,0,0.0,0.0,China PR,Shanghai Greenland Shenhua FC,48.0
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
(df['height_cm'] == 0).sum()

9743