In [66]:
import pandas as pd
import numpy as np

df = pd.read_csv('DataExtraction/players_20.csv',encoding='utf-8')
df.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

In [67]:
df.set_index('short_name', inplace=True)
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club','overall']]

In [68]:
df_restart_point = df.copy()

### Drop row

In [69]:
#Drop one row
#axis parameter
# df.drop('L. Messi', axis=0)
#index parameter
df.drop(index=['L. Messi'])
df

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91
...,...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48

In [70]:
#Drop 2 or more rows and update datafram(inplace=True)
df.drop(['L. Messi', 'Cristiano Ronaldo'],axis=0,inplace=True)
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City,91
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona,90

### Drop columns

In [71]:
df = df_restart_point.copy()

In [72]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91

In [73]:
#Drop one column
#axis parameter
# df.drop('long_name',axis=1)
#column parameter
df.drop(columns=['long_name'])

,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91
...,...,...,...,...,...,...,...
Shao Shuai,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48
Xiao Mingjie,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48
Zhang Wei,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48
Wang Haijian,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48
Pan Ximing,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48

In [74]:
#drop columns by position(drop second last column)
df.drop(df.columns[-2],axis=1)

,long_name,age,dob,height_cm,weight_kg,nationality,overall
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,91
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,48
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,48
Zhang Wei,张威,19,2000-05-16,186,75,China PR,48
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,48
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,48

In [75]:
#Drop 2 or more columns and update data(inplace = True)
df.drop(df.columns[0:3],axis=1,inplace=True)

In [76]:
df.head()

,height_cm,weight_kg,nationality,club,overall
short_name,,,,,
L. Messi,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,187,83,Portugal,Juventus,93
Neymar Jr,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,188,87,Slovenia,Atlético Madrid,91
E. Hazard,175,74,Belgium,Real Madrid,91

In [77]:
#testing
filtered_df = df.loc[df['overall'] > 88, ['height_cm', 'overall']]
filtered_df

                   height_cm  overall
short_name
L. Messi                 170       94
Cristiano Ronaldo        187       93
Neymar Jr                175       92
J. Oblak                 188       91
E. Hazard                175       91
K. De Bruyne             181       91
M. ter Stegen            187       90
V. van Dijk              193       90
L. Modrić                172       90
M. Salah                 175       90
K. Mbappé                178       89
K. Koulibaly             187       89
H. Kane                  188       89
Alisson                  191       89
De Gea                   192       89
N. Kanté                 168       89
G. Chiellini             187       89
S. Agüero                173       89
Sergio Ramos             184       89
L. Suárez                182       89
R. Lewandowski           184       89
Sergio Busquets          189       89
A. Griezmann             176       89

In [78]:
df.head()

,height_cm,weight_kg,nationality,club,overall
short_name,,,,,
L. Messi,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,187,83,Portugal,Juventus,93
Neymar Jr,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,188,87,Slovenia,Atlético Madrid,91
E. Hazard,175,74,Belgium,Real Madrid,91

In [79]:
df_restart_point

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91
...,...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48

### Create random sample with sample method

In [81]:
df = df_restart_point.copy()

In [82]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91

### sample()

In [108]:
#Extract 10 rando elements form nationality column
df['nationality'].sample(10, random_state=76)

short_name
P. Daka            Zambia
M. Feigenspan     Germany
C. Vidal           France
L. Gambin           Malta
F. Kanoute        Senegal
Ricardinho         Brazil
K. Hawley         England
�. Rusu           Romania
A. Hinestroza    Colombia
S. Özcan          Germany
Name: nationality, dtype: object

In [121]:
#extract a random 20% sample of the dataframe
#// -> floor division because 18278 is not divisible by 5
df.sample(18278//5).sort_values(by='overall',ascending=False)

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
M. Salah,Mohamed Salah Ghaly,27,1992-06-15,175,71,Egypt,Liverpool,90
H. Kane,Harry Kane,25,1993-07-28,188,89,England,Tottenham Hotspur,89
K. Koulibaly,Kalidou Koulibaly,28,1991-06-20,187,89,Senegal,Napoli,89
T. Kroos,Toni Kroos,29,1990-01-04,183,76,Germany,Real Madrid,88
...,...,...,...,...,...,...,...,...
S. Cartwright,Samuel Cartwright,18,2000-07-08,185,75,England,Peterborough United,48
Huang Jiahui,Jiahui Huang,18,2000-10-07,183,74,China PR,Dalian YiFang FC,48
L. Singh,Luke Singh,17,2001-09-01,184,72,Canada,Brøndby IF,48
M. Sagaf,Mohammed Sagaf,21,1997-11-12,177,70,England,Carlisle United,48
Song Min Kyu,송민규 Min Kyu Song,19,1999-09-12,179,72,Korea Republic,Pohang Steelers,48

In [123]:
#same as previous by frac method
df.sample(frac=0.2,random_state=35).sort_values(by='overall',ascending=False)

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Suárez,Luis Alberto Suárez Díaz,32,1987-01-24,182,86,Uruguay,FC Barcelona,89
De Gea,David De Gea Quintana,28,1990-11-07,192,82,Spain,Manchester United,89
Alisson,Alisson Ramses Becker,26,1992-10-02,191,91,Brazil,Liverpool,89
P. Aubameyang,Pierre-Emerick Aubameyang,30,1989-06-18,187,80,Gabon,Arsenal,88
S. Handanovič,Samir Handanovič,34,1984-07-14,193,92,Slovenia,Inter,88
...,...,...,...,...,...,...,...,...
G. Sykes-Kenworthy,George Sykes-Kenworthy,19,1999-10-01,182,78,England,Bradford City,48
H. Shirai,白井 陽斗,19,1999-10-23,170,60,Japan,Gamba Osaka,48
F. Nevarez,Francisco Nevarez,18,2000-12-03,178,69,Mexico,FC Juárez,48
Zhang Yufeng,张宇峰,21,1998-01-05,178,76,China PR,Beijing Renhe FC,48
J. Hope,Joseph Hope,17,2002-05-28,178,75,England,Grimsby Town,48

In [128]:
#upsample: increase the samping rate ->frac >1(Note: replace parameter has to be true for frac parameter > 1)
df.sample(frac=2,replace=True,random_state=23).sort_values(by=['overall'],ascending=False)

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
...,...,...,...,...,...,...,...,...
M. Sagaf,Mohammed Sagaf,21,1997-11-12,177,70,England,Carlisle United,48
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48
Liu Guobo,刘国博,19,1999-11-27,189,75,China PR,Beijing Sinobo Guoan FC,48
R. Wikberg,Robin Wikberg,16,2002-07-03,186,72,Sweden,Östersunds FK,48
A. De Angelis,Alessandro De Angelis,21,1998-03-13,174,62,Italy,Ascoli,48

In [131]:
df = df_restart_point.copy()
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91

### Filtering a df with query() method

### Query()

In [136]:
# select players older than 34
df.query('age>34')
# write the equivalent boolean slicing
df[df['age'] > 34]

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
Z. Ibrahimović,Zlatan Ibrahimović,37,1981-10-03,195,95,Sweden,LA Galaxy,85
Pepe,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto,84
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus,83
Casillas,Iker Casillas Fernández,38,1981-05-20,185,84,Spain,FC Porto,83
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria,83
...,...,...,...,...,...,...,...,...
N. Hunt,Nicky Hunt,35,1983-09-03,185,86,England,Crewe Alexandra,55
K. Ogi,荻 晃太,36,1983-05-05,185,76,Japan,Vissel Kobe,55
J. McCombe,Jamie McCombe,36,1983-01-01,196,79,England,Lincoln City,52
G. Maley,Gary Maley,36,1982-08-03,188,90,Scotland,Livingston FC,52
Zhou Ting,周挺,40,1979-02-05,182,73,China PR,Dalian YiFang FC,49

In [155]:
# select players older than 34 from italy
df.query('age > 34 and nationality == "Italy" ')
# write equivalent booleean slicing
ageroni = df['age'] > 34
italianoooo = df['nationality'] == 'Italy'
df[ageroni & italianoooo]

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus,83
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria,83
D. De Rossi,Daniele De Rossi,35,1983-07-24,184,83,Italy,Boca Juniors,82
A. Mirante,Antonio Mirante,35,1983-07-08,193,79,Italy,Roma,79
A. Diamanti,Alessandro Diamanti,36,1983-05-02,180,75,Italy,Western United FC,76
C. Maggio,Christian Maggio,37,1982-02-11,184,79,Italy,Benevento,74
D. Dainelli,Dario Dainelli,40,1979-06-09,191,78,Italy,Livorno,73
F. Marchetti,Federico Marchetti,36,1983-02-07,188,83,Italy,Genoa,73
F. Peluso,Federico Peluso,35,1984-01-20,188,82,Italy,Sassuolo,73
C. Terzi,Claudio Terzi,35,1984-06-19,180,69,Italy,Spezia,72
A. Rosina,Alessandro Rosina,35,1984-01-31,170,69,Italy,US Salernitana 1919,72
D. Maietta,Domenico Maietta,36,1982-08-03,184,75,Italy,Empoli,72
A. Cordaz,Alex Cordaz,36,1983-01-01,188,83,Italy,Crotone,72
S. Floccari,Sergio Floccari,37,1981-11-12,180,79,Italy,SPAL,72
M. Iori,Manuel Iori,37,1982-03-12,182,72,Italy,Cittadella,72
M. Stefani,Mirco Stefani,35,1984-01-25,180,80,Italy,Pordenone,71
G. Pegolo,Gianluca Pegolo,38,1981-03-25,183,76,Italy,Sassuolo,70
D. Gastaldello,Daniele Gastaldello,36,1983-06-25,185,77,Italy,Brescia,70
D. Moscardelli,Davide Moscardelli,39,1980-02-03,185,80,Italy,Pisa,70
E. Calaiò,Emanuele Calaiò,37,1982-01-08,179,75,Italy,US Salernitana 1919,70
D. Croce,Daniele Croce,36,1982-09-09,173,70,Italy,US Cremonese,69
A. Rosati,Antonio Rosati,36,1983-06-26,195,88,Italy,Torino,69
F. Mazzeo,Fabio Mazzeo,35,1983-07-24,177,77,Italy,Livorno,69
M. De Agostini,Michele De Agostini,35,1983-11-27,180,78,Italy,Pordenone,69
A. Pomini,Alberto Pomini,38,1981-03-17,185,80,Italy,Venezia FC,68
F. Evacuo,Felice Evacuo,36,1982-08-23,187,88,Italy,Trapani,67
G. Munari,Gianni Munari,36,1983-06-24,190,84,Italy,Parma,67
L. Pagliarulo,Luca Pagliarulo,35,1984-02-29,187,80,Italy,Trapani,67
C. Del Grosso,Cristiano Del Grosso,36,1983-03-24,171,66,Italy,Pescara,66
R. Vitiello,Roberto Vitiello,36,1983-05-08,176,72,Italy,Castellammare di Stabia,65
A. Bruno,Alessandro Bruno,35,1983-07-04,180,70,Italy,Pescara,65
T. Berni,Tommaso Berni,36,1983-03-06,185,80,Italy,Inter,64
P. Gori,Pier Graziano Gori,39,1980-05-10,189,83,Italy,Benevento,62
S. Farelli,Simone Farelli,36,1983-02-19,186,82,Italy,Pescara,58

In [164]:
# add not operator to the first example ~ !=
df.query('not(age>34)')

# write equivalent boolean slicing
df[~(df['age'] > 34)]

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91
...,...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48

In [181]:
# convert height to metres
df.rename(columns={'height_cm': 'height_m'}, inplace=True)
df['height_m'] = df['height_m'] / 100
df.head()

,long_name,age,dob,height_m,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,1.70,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,1.87,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,1.75,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,1.88,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,1.75,74,Belgium,Real Madrid,91

In [184]:
# select all with height > 1.8m
df.query('height_m>1.8')

# write equivalent boolean slicing
df[df['height_m'] > 1.8]

,long_name,age,dob,height_m,weight_kg,nationality,club,overall
short_name,,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,1.87,83,Portugal,Juventus,93
J. Oblak,Jan Oblak,26,1993-01-07,1.88,87,Slovenia,Atlético Madrid,91
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,1.81,70,Belgium,Manchester City,91
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,1.87,85,Germany,FC Barcelona,90
V. van Dijk,Virgil van Dijk,27,1991-07-08,1.93,92,Netherlands,Liverpool,90
...,...,...,...,...,...,...,...,...
P. Martin,Paul Martin,20,1999-01-05,1.88,84,Republic of Ireland,Waterford FC,48
Shao Shuai,邵帅,22,1997-03-10,1.86,79,China PR,Beijing Renhe FC,48
Zhang Wei,张威,19,2000-05-16,1.86,75,China PR,Hebei China Fortune FC,48
Wang Haijian,汪海健,18,2000-08-02,1.85,74,China PR,Shanghai Greenland Shenhua FC,48
Pan Ximing,潘喜明,26,1993-01-11,1.82,78,China PR,Hebei China Fortune FC,48

In [199]:
# select players born after 1990
# check data type
df.dtypes
# convert dob column to datetime type
df['dob'] = pd.to_datetime(df['dob'], errors='coerce')
df.dtypes
# query
df['dob'].dt.year
df.query('dob.dt.year>1990')
# write equivalent boolean slicing
df[df['dob'].dt.year > 1990]

,long_name,age,dob,height_m,weight_kg,nationality,club,overall
short_name,,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,1.75,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,1.88,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,1.75,74,Belgium,Real Madrid,91
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,1.81,70,Belgium,Manchester City,91
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,1.87,85,Germany,FC Barcelona,90
...,...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,1.86,79,China PR,Beijing Renhe FC,48
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,1.77,66,China PR,Shanghai SIPG FC,48
Zhang Wei,张威,19,2000-05-16,1.86,75,China PR,Hebei China Fortune FC,48
Wang Haijian,汪海健,18,2000-08-02,1.85,74,China PR,Shanghai Greenland Shenhua FC,48
Pan Ximing,潘喜明,26,1993-01-11,1.82,78,China PR,Hebei China Fortune FC,48