In [1]:
import pandas as pd
import numpy as np

In [2]:
df_laptops = pd.read_csv('FilteringData/laptop_price.csv', encoding='unicode_escape')
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [3]:
#using np.select for more than 2 choices
#creating an array based on multiple price tiers (>2 choices)
#creating 'conditions' and 'values' variables
price_conditions = [
    df_laptops['Price_euros'] < 1200,
    (df_laptops['Price_euros'] >= 1200) & (df_laptops['Price_euros'] <= 1900),
    df_laptops['Price_euros'] > 1900
]

prices_values = ['Cheap','Mid Tier', 'Expensive']

#creating a new column to match the values to the price connditions with np.select()
df_laptops['Price_tier'] = np.select(price_conditions,prices_values,default='Unknown')

In [4]:
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Mid Tier
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Cheap
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Mid Tier

In [5]:
#isin():Single filtering
#Select Apple or HP Laptops
df_laptops['Company'].isin(['Apple','HP'])

0        True
1        True
2        True
3        True
4        True
        ...
1298    False
1299    False
1300    False
1301     True
1302    False
Name: Company, Length: 1303, dtype: bool

In [6]:
#filter dataframe
df_laptops[df_laptops['Company'].isin(['Apple','HP'])]

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Mid Tier
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Cheap
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Mid Tier
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1282,1300,HP,Stream 11-Y000na,Netbook,11.6,1366x768,Intel Celeron Dual Core N3060 1.6GHz,2GB,32GB Flash Storage,Intel HD Graphics 400,Windows 10,1.17kg,209.00,Cheap
1287,1305,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Cheap
1294,1312,HP,Pavilion 15-AW003nv,Notebook,15.6,Full HD 1920x1080,AMD A9-Series 9410 2.9GHz,6GB,1.0TB Hybrid,AMD Radeon R7 M440,Windows 10,2.04kg,549.99,Cheap
1296,1314,HP,Stream 11-Y000na,Netbook,11.6,1366x768,Intel Celeron Dual Core N3060 1.6GHz,2GB,32GB Flash Storage,Intel HD Graphics 400,Windows 10,1.17kg,209.00,Cheap
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Cheap

In [7]:
#isin(): Multiple filtering
#find notebooks or ultrabooks from Apple or HP
filter1 = df_laptops['TypeName'].isin(['Notebook','Ultrabook'])
filter2 = df_laptops['Company'].isin(['HP','Apple'])
df_laptops[filter1 & filter2]

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Mid Tier
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Cheap
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Mid Tier
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1273,1291,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Cheap
1280,1298,HP,Pavilion 15-AW003nv,Notebook,15.6,Full HD 1920x1080,AMD A9-Series 9410 2.9GHz,6GB,1.0TB Hybrid,AMD Radeon R7 M440,Windows 10,2.04kg,549.99,Cheap
1287,1305,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Cheap
1294,1312,HP,Pavilion 15-AW003nv,Notebook,15.6,Full HD 1920x1080,AMD A9-Series 9410 2.9GHz,6GB,1.0TB Hybrid,AMD Radeon R7 M440,Windows 10,2.04kg,549.99,Cheap
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Cheap

In [8]:
df_laptops[filter1 & filter2].value_counts('Company')

Company
HP       220
Apple     21
Name: count, dtype: int64

In [9]:
#Find duplicates in 1 column/series (laptop_ID)
df_laptops[df_laptops.duplicated('laptop_ID')]

Empty DataFrame
Columns: [laptop_ID, Company, Product, TypeName, Inches, ScreenResolution, Cpu, Ram, Memory, Gpu, OpSys, Weight, Price_euros, Price_tier]
Index: []

In [10]:
#Duplicates in 2 or more columns
df_laptops[df_laptops.duplicated(['Product','TypeName','Inches'])]

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Mid Tier
6,7,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.2GHz,16GB,256GB Flash Storage,Intel Iris Pro Graphics,Mac OS X,2.04kg,2139.97,Expensive
7,8,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,256GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,1158.70,Cheap
10,11,HP,250 G6,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,No OS,1.86kg,393.90,Cheap
11,12,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,4GB,500GB HDD,Intel HD Graphics 520,No OS,1.86kg,344.99,Cheap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00,Cheap
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00,Mid Tier
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00,Cheap
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Cheap
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00,Cheap

In [11]:
#Sort dataframe ascending by company and price
#Cheapest first and most expensive last
df_laptops = df_laptops.sort_values(['Company','Price_euros']) 
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier
1215,1233,Acer,C740-C9QX (3205U/2GB/32GB/Chrome,Netbook,11.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,2GB,32GB SSD,Intel HD Graphics,Chrome OS,1.3kg,174.0,Cheap
290,295,Acer,Chromebook C910-C2ST,Notebook,15.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,2GB,16GB SSD,Intel HD Graphics,Chrome OS,2.19kg,199.0,Cheap
1102,1117,Acer,Chromebook 15,Notebook,15.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,4GB,16GB SSD,Intel HD Graphics,Chrome OS,2.20kg,209.0,Cheap
695,703,Acer,TravelMate B117-M,Netbook,11.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,32GB Flash Storage,Intel HD Graphics,Windows 10,1.4kg,269.0,Cheap
1198,1216,Acer,Aspire 3,Notebook,15.6,1366x768,Intel Celeron Dual Core N3350 2GHz,4GB,1TB HDD,Intel HD Graphics 500,Linux,2.1kg,272.0,Cheap

In [12]:
df_laptops

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier
1215,1233,Acer,C740-C9QX (3205U/2GB/32GB/Chrome,Netbook,11.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,2GB,32GB SSD,Intel HD Graphics,Chrome OS,1.3kg,174.00,Cheap
290,295,Acer,Chromebook C910-C2ST,Notebook,15.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,2GB,16GB SSD,Intel HD Graphics,Chrome OS,2.19kg,199.00,Cheap
1102,1117,Acer,Chromebook 15,Notebook,15.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,4GB,16GB SSD,Intel HD Graphics,Chrome OS,2.20kg,209.00,Cheap
695,703,Acer,TravelMate B117-M,Netbook,11.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,32GB Flash Storage,Intel HD Graphics,Windows 10,1.4kg,269.00,Cheap
1198,1216,Acer,Aspire 3,Notebook,15.6,1366x768,Intel Celeron Dual Core N3350 2GHz,4GB,1TB HDD,Intel HD Graphics 500,Linux,2.1kg,272.00,Cheap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,195,Vero,K147 (N3350/4GB/32GB/FHD/W10),Notebook,14.0,IPS Panel Full HD 1920x1080,Intel Celeron Dual Core N3350 1.1GHz,4GB,32GB Flash Storage,Intel HD Graphics 500,Windows 10,1.3kg,260.00,Cheap
877,888,Xiaomi,Mi Notebook,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8GB,256GB SSD,Nvidia GeForce 940MX,Windows 10,1.28kg,935.00,Cheap
192,196,Xiaomi,Mi Notebook,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Nvidia GeForce MX150,No OS,1.3kg,999.90,Cheap
184,188,Xiaomi,Mi Notebook,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,Nvidia GeForce MX150,No OS,1.95kg,1199.00,Cheap
514,521,Xiaomi,Mi Notebook,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,16GB,256GB SSD,Nvidia GeForce MX150,No OS,1.95kg,1399.95,Mid Tier

In [13]:
#Checking for all values in "Company" column
df_laptops['Company'].value_counts()

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Mediacom       7
Razer          7
Microsoft      6
Vero           4
Xiaomi         4
Chuwi          3
Fujitsu        3
LG             3
Google         3
Huawei         2
Name: count, dtype: int64

In [14]:
#Duplicated values in "Company" columns (default -> keep='first')
duplicated_first = df_laptops.duplicated('Company',keep='first')
duplicated_first

1215    False
290      True
1102     True
695      True
1198     True
        ...
191      True
877     False
192      True
184      True
514      True
Length: 1303, dtype: bool

In [15]:
#Show dataframe with duplicated values in "Company" column
df_laptops[duplicated_first] 
#Keep first (Cheapest laptop per company)
#Show DF with non duplicated values in "Company" column
# ~ is the not operator
df_laptops[~duplicated_first][['Company','Price_euros','Inches']]

        Company  Price_euros  Inches
1215       Acer       174.00    11.6
1         Apple       898.94    13.3
20         Asus       191.90    11.6
30        Chuwi       244.99    15.6
340        Dell       274.90    15.6
983     Fujitsu       649.00    15.6
472      Google      1275.00    12.3
1268         HP       209.00    11.6
170      Huawei      1349.00    13.0
909          LG      1899.00    14.0
1272     Lenovo       229.00    14.0
1169        MSI       839.00    15.6
626    Mediacom       239.00    14.0
457   Microsoft       989.00    13.5
1117      Razer      1029.00    12.5
430     Samsung       269.00    11.6
159     Toshiba       447.00    15.6
1120       Vero       196.00    13.3
877      Xiaomi       935.00    13.3

In [16]:
#Check all value companies
df_laptops[~duplicated_first].value_counts('Company')

Company
Acer         1
Apple        1
Asus         1
Chuwi        1
Dell         1
Fujitsu      1
Google       1
HP           1
Huawei       1
LG           1
Lenovo       1
MSI          1
Mediacom     1
Microsoft    1
Razer        1
Samsung      1
Toshiba      1
Vero         1
Xiaomi       1
Name: count, dtype: int64

In [17]:
#now the same with most expensive laptop
df_laptops = df_laptops.sort_values(
    by=['Company', 'Price_euros'], 
    ascending=[True, False]
)
df_laptops
duplicated_most_expensive = df_laptops.duplicated('Company',keep='first')
df_laptops[~duplicated_most_expensive][['Company','Price_euros']]

        Company  Price_euros
1189       Acer      2599.00
17        Apple      2858.00
1066       Asus      3975.00
421       Chuwi       449.00
723        Dell      3659.40
623     Fujitsu       799.00
437      Google      2199.00
749          HP      4389.00
214      Huawei      1499.00
678          LG      2299.00
610      Lenovo      4899.00
177         MSI      2799.00
580    Mediacom       389.00
449   Microsoft      2589.00
196       Razer      6099.00
874     Samsung      1849.00
491     Toshiba      2799.00
191        Vero       260.00
514      Xiaomi      1399.95

In [18]:
(df_laptops['Company'] == 'Vero').sum()

np.int64(4)

In [19]:
#drop duplicates in 2 or more columns
df_laptops.drop_duplicates(['Company']).value_counts(['Company'])

Company
Acer         1
Apple        1
Asus         1
Chuwi        1
Dell         1
Fujitsu      1
Google       1
HP           1
Huawei       1
LG           1
Lenovo       1
MSI          1
Mediacom     1
Microsoft    1
Razer        1
Samsung      1
Toshiba      1
Vero         1
Xiaomi       1
Name: count, dtype: int64

In [22]:
#sort dataframe ascending by company and price
#cheapest first and most expensive last
df_laptops = df_laptops.sort_values(['Company','Price_euros'],ascending=True)
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier
1215,1233,Acer,C740-C9QX (3205U/2GB/32GB/Chrome,Netbook,11.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,2GB,32GB SSD,Intel HD Graphics,Chrome OS,1.3kg,174.0,Cheap
290,295,Acer,Chromebook C910-C2ST,Notebook,15.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,2GB,16GB SSD,Intel HD Graphics,Chrome OS,2.19kg,199.0,Cheap
1102,1117,Acer,Chromebook 15,Notebook,15.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,4GB,16GB SSD,Intel HD Graphics,Chrome OS,2.20kg,209.0,Cheap
695,703,Acer,TravelMate B117-M,Netbook,11.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,32GB Flash Storage,Intel HD Graphics,Windows 10,1.4kg,269.0,Cheap
1198,1216,Acer,Aspire 3,Notebook,15.6,1366x768,Intel Celeron Dual Core N3350 2GHz,4GB,1TB HDD,Intel HD Graphics 500,Linux,2.1kg,272.0,Cheap

In [28]:
#Cheapest: keep='first'
df_laptops.drop_duplicates(['Company'], keep='first')[['Company','Price_euros']]

        Company  Price_euros
1215       Acer       174.00
1         Apple       898.94
20         Asus       191.90
30        Chuwi       244.99
340        Dell       274.90
983     Fujitsu       649.00
472      Google      1275.00
1268         HP       209.00
170      Huawei      1349.00
909          LG      1899.00
1272     Lenovo       229.00
1169        MSI       839.00
626    Mediacom       239.00
457   Microsoft       989.00
1117      Razer      1029.00
430     Samsung       269.00
159     Toshiba       447.00
1120       Vero       196.00
877      Xiaomi       935.00

In [36]:
#most expensive keep='last'
df_laptops.drop_duplicates(['Company'],keep='last')[['Company','Price_euros']]

      Company  Price_euros
0        Acer      2599.00
1       Apple      2858.00
2        Asus      3975.00
3       Chuwi       449.00
4        Dell      3659.40
5     Fujitsu       799.00
6      Google      2199.00
7          HP      4389.00
8      Huawei      1499.00
9          LG      2299.00
10     Lenovo      4899.00
11        MSI      2799.00
12   Mediacom       389.00
13  Microsoft      2589.00
14      Razer      6099.00
15    Samsung      1849.00
16    Toshiba      2799.00
17       Vero       260.00
18     Xiaomi      1399.95

In [42]:
#arguments
#inplace: drop duplicates in place or return to a copy
#ignore_index=True : the resulting axis will be labelled 0,1, ...
df_laptops.drop_duplicates(['Company'],keep='last',inplace=True,ignore_index=True)
df_laptops[['Company','Price_euros']]

      Company  Price_euros
0        Acer      2599.00
1       Apple      2858.00
2        Asus      3975.00
3       Chuwi       449.00
4        Dell      3659.40
5     Fujitsu       799.00
6      Google      2199.00
7          HP      4389.00
8      Huawei      1499.00
9          LG      2299.00
10     Lenovo      4899.00
11        MSI      2799.00
12   Mediacom       389.00
13  Microsoft      2589.00
14      Razer      6099.00
15    Samsung      1849.00
16    Toshiba      2799.00
17       Vero       260.00
18     Xiaomi      1399.95

In [44]:
#sort dataframe ascending by company and inches
#smallest first and biggest last
df_laptops_new = pd.read_csv('FilteringData/laptop_price.csv', encoding='unicode_escape')
df_laptops_new = df_laptops_new.sort_values(by=['Company', 'Inches'])
df_laptops_new

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
319,324,Acer,TravelMate B,Notebook,11.6,1366x768,Intel Pentium Quad Core N3710 1.6GHz,4GB,128GB Flash Storage,Intel HD Graphics 405,Windows 10,1.4kg,485.00
461,468,Acer,TravelMate B,Netbook,11.6,1366x768,Intel Celeron Dual Core N3060 1.6GHz,4GB,128GB SSD,Intel HD Graphics 400,Windows 10,1.4kg,435.00
560,567,Acer,Spin SP111-31,2 in 1 Convertible,11.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Celeron Dual Core N3350 2.0GHz,4GB,32GB Flash Storage,Intel HD Graphics 500,Windows 10,1.25kg,349.00
619,626,Acer,CB5-132T-C9KK (N3160/4GB/32GB/Chrome,2 in 1 Convertible,11.6,IPS Panel Touchscreen 1366x768,Intel Celeron Quad Core N3160 1.6GHz,4GB,32GB Flash Storage,Intel HD Graphics 400,Chrome OS,1.25kg,379.00
695,703,Acer,TravelMate B117-M,Netbook,11.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,32GB Flash Storage,Intel HD Graphics,Windows 10,1.4kg,269.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1041,1055,Vero,V142 (X5-Z8350/2GB/32GB/W10),Notebook,14.0,1366x768,Intel Atom X5-Z8350 1.44GHz,2GB,32GB Flash Storage,Intel HD Graphics 400,Windows 10,1.45kg,210.80
192,196,Xiaomi,Mi Notebook,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Nvidia GeForce MX150,No OS,1.3kg,999.90
877,888,Xiaomi,Mi Notebook,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8GB,256GB SSD,Nvidia GeForce 940MX,Windows 10,1.28kg,935.00
184,188,Xiaomi,Mi Notebook,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,Nvidia GeForce MX150,No OS,1.95kg,1199.00
514,521,Xiaomi,Mi Notebook,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,16GB,256GB SSD,Nvidia GeForce MX150,No OS,1.95kg,1399.95

In [46]:
#smallest: keep='first'
df_laptops_new.drop_duplicates(['Company'],keep='first')[['Company','Inches']]

        Company  Inches
319        Acer    11.6
1234      Apple    11.6
20         Asus    11.6
421       Chuwi    12.3
455        Dell    11.6
567     Fujitsu    15.6
437      Google    12.3
677          HP    11.6
170      Huawei    13.0
909          LG    14.0
50       Lenovo    10.1
785         MSI    14.0
429    Mediacom    11.6
70    Microsoft    13.5
816       Razer    12.5
430     Samsung    11.6
963     Toshiba    12.5
1120       Vero    13.3
192      Xiaomi    13.3

In [47]:
#largest: keep='last'
df_laptops_new.drop_duplicates(['Company'],keep='last')[['Company','Inches']]

        Company  Inches
1216       Acer    17.3
17        Apple    15.4
1256       Asus    17.3
483       Chuwi    15.6
1243       Dell    17.3
983     Fujitsu    15.6
762      Google    12.3
1136         HP    17.3
214      Huawei    13.0
905          LG    15.6
1217     Lenovo    17.3
177         MSI    18.4
718    Mediacom    14.0
670   Microsoft    13.5
830       Razer    17.3
593     Samsung    15.6
1042    Toshiba    15.6
1041       Vero    14.0
514      Xiaomi    15.6

In [49]:
#unique values
#get unique elements in "Company" column
df_laptops = df_laptops_new
df_laptops['Company'].unique()

array(['Acer', 'Apple', 'Asus', 'Chuwi', 'Dell', 'Fujitsu', 'Google',
       'HP', 'Huawei', 'LG', 'Lenovo', 'MSI', 'Mediacom', 'Microsoft',
       'Razer', 'Samsung', 'Toshiba', 'Vero', 'Xiaomi'], dtype=object)

In [51]:
#getting unique element in the inches column
unique_inches = df_laptops['Inches'].unique()
unique_inches

array([11.6, 13.3, 14. , 15.6, 17.3, 12. , 15.4, 12.5, 14.1, 12.3, 15. ,
       17. , 13. , 10.1, 11.3, 13.9, 18.4, 13.5])

In [52]:
#getting the length of the unique elements
len(unique_inches)

18

In [ ]:
#nunique(): number of unique values
#get the number of unique elements in the 'Company' column 
df_laptops['Company'].nunique()

19

In [54]:
#get the number of unique elements in the 'Inches' column 
df_laptops['Inches'].nunique()

18