In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('DataExtraction/players_20.csv',encoding='utf-8')
df.set_index('short_name',inplace=True)
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club','overall']]

In [3]:
df_restart_point = df.copy()

In [4]:
df_restart_point

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91
...,...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48

In [5]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91

### Lambda function

In [6]:
# basic function
def sum_values(a,b):
    c = a + b
    return c

In [7]:
print(sum_values(3,4))

7

In [8]:
#Lambda function (one liner)
sum_values_lambda = lambda d,e: d+e

In [9]:
sum_values_lambda(3,4)

7

### Apply + Lambda function

In [10]:
#Use lambda function to convert "height_cm" to metres
lambda_height = df['height_cm'].apply(lambda m:(m/100))
lambda_height.head()

short_name
L. Messi             1.70
Cristiano Ronaldo    1.87
Neymar Jr            1.75
J. Oblak             1.88
E. Hazard            1.75
Name: height_cm, dtype: float64

In [11]:
#Use lambda function to convert "long_name" to upper case
lambda_upper_case = df['long_name'].apply(lambda ln:ln.upper())
lambda_upper_case.head()
#alternative with str attribute
non_lambda_upper = df['long_name'].str.upper()
non_lambda_upper.head()

short_name
L. Messi                  LIONEL ANDRÉS MESSI CUCCITTINI
Cristiano Ronaldo    CRISTIANO RONALDO DOS SANTOS AVEIRO
Neymar Jr                  NEYMAR DA SILVA SANTOS JUNIOR
J. Oblak                                       JAN OBLAK
E. Hazard                                    EDEN HAZARD
Name: long_name, dtype: object

In [12]:
df.dtypes

long_name      object
age             int64
dob            object
height_cm       int64
weight_kg       int64
nationality    object
club           object
overall         int64
dtype: object

In [13]:
df['dob'] = df['dob'].astype('datetime64')
#use lambda function to get the year of the "dob" series
year_lambda = df['dob'].apply(lambda x:x.year)
year_lambda.head()

short_name
L. Messi             1987
Cristiano Ronaldo    1985
Neymar Jr            1992
J. Oblak             1993
E. Hazard            1991
Name: dob, dtype: int64

In [14]:
df['height_cm'] = df['height_cm'].apply(lambda x:x/100)

In [15]:
df.rename(columns={'height_cm': 'height_m'}, inplace=True)
# apply lambda function to calculateBMI(weight/height*height)
lambda_BMI = df.apply(lambda x:x['weight_kg']/(x['height_m']**2),axis=1)
lambda_BMI

short_name
L. Messi             24.913495
Cristiano Ronaldo    23.735308
Neymar Jr            22.204082
J. Oblak             24.615211
E. Hazard            24.163265
                       ...
Shao Shuai           22.835010
Xiao Mingjie         21.066743
Zhang Wei            21.678807
Wang Haijian         21.621622
Pan Ximing           23.547881
Length: 18278, dtype: float64

In [16]:
df

,long_name,age,dob,height_m,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,1.70,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,1.87,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,1.75,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,1.88,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,1.75,74,Belgium,Real Madrid,91
...,...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,1.86,79,China PR,Beijing Renhe FC,48
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,1.77,66,China PR,Shanghai SIPG FC,48
Zhang Wei,张威,19,2000-05-16,1.86,75,China PR,Hebei China Fortune FC,48
Wang Haijian,汪海健,18,2000-08-02,1.85,74,China PR,Shanghai Greenland Shenhua FC,48
Pan Ximing,潘喜明,26,1993-01-11,1.82,78,China PR,Hebei China Fortune FC,48

### Making a copy with copy()

#### Deep = True -> changes to original DF will NOT be reflected in the copy

In [17]:
df_copy = df.copy()
df_copy.head()

,long_name,age,dob,height_m,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,1.70,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,1.87,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,1.75,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,1.88,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,1.75,74,Belgium,Real Madrid,91

#### Deep = False -> changes to original DF will be reflected in the copy

In [18]:
df_shallow_copy = df_copy.copy(deep=False)
df_copy.loc['L. Messi','height_m'] = 1.80

In [19]:
df_copy.head()

,long_name,age,dob,height_m,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,1.80,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,1.87,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,1.75,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,1.88,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,1.75,74,Belgium,Real Madrid,91

In [20]:
df_shallow_copy.head()

,long_name,age,dob,height_m,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,1.80,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,1.87,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,1.75,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,1.88,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,1.75,74,Belgium,Real Madrid,91

In [21]:
df.head()

,long_name,age,dob,height_m,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,1.70,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,1.87,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,1.75,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,1.88,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,1.75,74,Belgium,Real Madrid,91